channels:
  - conda-forge
dependencies:
   - scipy==1.6.2
   - hickle==3.4.5
   - seaborn==0.11.1
   - numpy==1.20.1
   - netCDF4==1.5.6
   - matplotlib==3.5.1
   - cartopy==0.18.0
   - logging==0.5.1.2